### PR TITLE
The Big Breakup: CuratorCMS and LearningCurator.ca publishing model changes

### PR DESCRIPTION
**Pull request by allanhaggett**
OK this marks a fairly fundamental shift in the approach we're taking. While it actually doesn't change the codebase all that much, the publishing model is considerably altered in order to better accommodate a modern hosting environment (e.g. DevExchange OpenShift). We are essentially breaking things up into: 

- backend authoring tool for curators (dynamic PHP direct database interface)
- front-end interface for learners (static HTML)
- learner activity tracking (javascript <-> couchDB)
- search (javascript > elasticsearch)

The CakePHP generated website becomes a curator-only administrative backend (CuratorCMS.ca) which publishes a _static_ version (LearningCuratror.ca) of the site that can be easily deployed to any hosting platform. The curator-only side is now invite-only (removes need for SiteMinder auth method), whereby a main site admin controls access to it by manually creating accounts and providing new people with a password (that they then must change).

The UI is the biggest change, as the home page of the CMS is now oriented towards curators who construct their pathways in a "preview" mode, and need to click a "publish" button, which "bakes" a static HTML version of the pathway page (saved into the new /static/ folder in the root of the project). As of this pull request, the static front-end of the site is a dramatically paired-down/streamlined version of our core concept. The idea is to re-build the interface to make it better while incorporating the best of the previous design. 

As a part of all this, we have moved all user claim activity storage onto the client (localstorage via [pouchdb](https://pouchdb.com/) currently). We used to store which activities folks claim directly in the same database (e.g. activities_users table) as the pathway data, we are now separating this concern out. My current plan is to start out with local-only (with a warning to users that dumping their cache will dump their progress) while we determine which method of backing up the info is best: 

1. moving forward with pouchdb and standing up a couchdb server to synchronize local->cloud transparently
2. deploy the whole thing as an [Electron](https://github.com/electron/electron) app
3. keep using the same database, but communicate with it via API?
4. Something else entirely

As well, search becomes a consideration. Currently, I am hoping to finish my work standing up an ElasticSearch instance that plugs into the CMS (as you add new things, the ES instance is updated), which would allow us to query the index through javascript on the front-end. Failing this, a more simple API could be built to the existing database.

This merge into the master branch is the essentially the bare minimum of changes in order to facilitate this new model and it still requires much work to make it a viable platform. I'm merging this early so that we can do test deploys into OCP4 on DevExchange OpenShift. 

Thank you for reading this essay of a pull request :)

### CODE REVIEW

**Comment by allanhaggett** [comment]
@Kousthubha-M you should be able to pull these changes in and hopefully those errors will cease and we can get things up and running? Feel free to reach out at any point to chat. I'm thinking that I'll record my screen as I stand up and new instance so you can see exactly what I'm doing and we can figure out what I'm missing in the documentation of the build process.

Cheers

**Comment by allanhaggett** [comment]
@Kousthubha-M are you using this repo in the build process? or your fork?

👍

**Comment by Kousthubha-M** [comment]
@allanhaggett I pulled the changes to my cloned repo and using that.

**Comment by allanhaggett** [comment]
Thanks for the clarification :)

**Pull request merged**
